// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistEnferHos.Infra.Contexts;

namespace SistEnferHos.Infra.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistEnferHos.Domain.Entities.Hospital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("HosEndereco")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CNPJNumber")
                        .IsRequired()
                        .HasColumnName("CNPJ")
                        .HasColumnType("varchar(18)");

                    b.Property<int>("DocumentType")
                        .HasColumnName("HosTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("HosNome")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("HosHospital");
                });

            modelBuilder.Entity("SistEnferHos.Domain.Entities.Nurse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired()
                        .HasColumnName("EnfDataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Coren")
                        .IsRequired()
                        .HasColumnName("COREN")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("CpfNumer")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasColumnType("varchar(14)");

                    b.Property<int>("DocumentType")
                        .HasColumnName("EnfTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("EnfNome")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("HospitalId");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("EnfEnfermeiro");
                });

            modelBuilder.Entity("SistEnferHos.Domain.Entities.Nurse", b =>
                {
                    b.HasOne("SistEnferHos.Domain.Entities.Hospital", "Hospital")
                        .WithMany("Nurses")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
